apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.19-alpine3.22
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: netbox
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: netbox-postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: netbox-postgres-secret
              key: POSTGRES_PASSWORD

