apiVersion: v1
kind: Namespace
metadata: 
  name: homepage-prod
  labels: 
    app: homepage
    env: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-prod
  namespace: homepage-prod
  labels:
    app: homepage
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homepage
      env: prod
  template:
    metadata:
      labels:
        app: homepage
        env: prod
    spec:
      containers:
      - name: homepage-prod
        image: rschouweiler/docker-homepage:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-prod
  namespace: homepage-prod
spec:
  type: NodePort
  selector:
    app: homepage
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
