apiVersion: v1
kind: Namespace
metadata: 
  name: homepage-stag
  labels: 
    app: homepage
    env: stag
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-stag
  namespace: homepage-stag
  labels:
    app: homepage
    env: stag
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homepage
      env: stag
  template:
    metadata:
      labels:
        app: homepage
        env: stag
    spec:
      containers:
      - name: homepage-stag
        image: rschouweiler/docker-homepage:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: gitlab-reg-creds
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-stag
  namespace: homepage-stag
spec:
  type: NodePort
  selector:
    app: homepage
    env: stag
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
