apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-stag
  labels:
    app: homepage
    env: stag
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homepage
      env: stag
  template:
    metadata:
      labels:
        app: homepage
        env: stag
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
