---
apiVersion: v1
kind: Namespace
metadata: 
  name: homepage-prod
  labels: 
    app: homepage
    env: prod
---
apiVersion: v1
kind: Namespace
metadata: 
  name: homepage-stag
  labels: 
    app: homepage
    env: stag
